apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          # Placeholder image - the GitHub Action will replace this dynamically
          image: europe-west3-docker.pkg.dev/cs-project-r08ugfup/my-go-repo/go-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  type: LoadBalancer
  selector:
    app: go-server
  ports:
    - port: 80
      targetPort: 8080